---
name: CD

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  information:
    name: ℹ Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      description: ${{ steps.information.outputs.description }}
      name: ${{ steps.information.outputs.name }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: ⏭ Copy add-on files
        run: |
          cp add-ons/common/Dockerfile add-ons/ps5-mqtt-edge
          cp add-ons/common/build.yaml add-ons/ps5-mqtt-edge
          cp add-ons/common/.dockerignore add-ons/ps5-mqtt-edge
      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4
        with:
          path: "./add-ons/ps5-mqtt-edge"

  static-analysis:
    name: ✅ Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: ⤵ Check out repository
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3
        with:
          node-version: 24.16.0

      - name: 🧶 Enable Corepack
        run: corepack enable

      - name: ⏬ Install dependencies
        run: yarn install --immutable

      - name: 🎨 Check formatting
        run: yarn format/check

      - name: 🔍 Run typecheck
        run: yarn typecheck

      - name: 🧹 Run lint
        run: yarn lint

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⤵ Check out repository
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3
        with:
          node-version: 24.16.0

      - name: 🧶 Enable Corepack
        run: corepack enable

      - name: ⏬ Install dependencies
        run: yarn install --immutable

      - name: 🧪 Run tests
        run: yarn test

  build:
    needs: [information, static-analysis, test]
    runs-on: ubuntu-latest
    name: 🏭 Build add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: ⤵ Check out repository
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3
        with:
          node-version: 24.16.0

      - name: 🧶 Enable Corepack
        run: corepack enable

      - name: ⏬ Install dependencies
        run: yarn install --immutable

      - name: 👨‍🏭 Build App
        run: yarn build

      - name: ⏭ Copy App Files
        run: |
          rsync -a --exclude='.git' --exclude='add-ons' ./ add-ons/ps5-mqtt-edge/
          cp add-ons/common/Dockerfile add-ons/ps5-mqtt-edge
          cp add-ons/common/build.yaml add-ons/ps5-mqtt-edge
          cp add-ons/common/.dockerignore add-ons/ps5-mqtt-edge

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏭 Build & Deploy ${{ matrix.arch }} add-on - Dev
        uses: home-assistant/builder@master
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/add-ons/ps5-mqtt-edge \
            --version dev \
            --additional-tag ${{ github.sha }} \
            --no-latest \
            --image "ps5-mqtt/${{ matrix.arch }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
